# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'Shop' do
  use_frameworks!
  pod 'SwiftLint'
  pod 'Alamofire', '~> 4.7'
  pod 'OHHTTPStubs/Swift'
  pod 'Fabric'
  pod 'Crashlytics'
end

target 'ShopTests' do
    inherit! :search_paths
    pod 'Alamofire', '~> 4.7'
    pod 'OHHTTPStubs/Swift'
end
